---
include:
  - board: nice_nano_v2
    shield: crosses_left
    artifact: crosses36_left
  - board: nice_nano_v2
    shield: crosses_right
    artifact: crosses36_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
